### ISSUE TITLE
liveness probe issue with group exclude database condition

### ISSUE THREAD

**Issue by shivrajjadhav733** [alexandreroman/spring-k8s-probes-demo#1]
I upgraded springboot version to 2.3. With that I started seeing default endpoints like /actuator/health/readiness and /actuator/health/liveness
I see both are those are UP.

However, to suffice need of the two scenarios:

1. Liveness probe should not include backend setup checks like DB. Only want to restart when app is unhealthy.
2. Readiness probe should include backend setup like DB.

I updated my application yaml like below

```
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-components: always
      group:
        readiness:
          include:
          - db
        liveness:
          exclude:
          - db

```
updated health path in deployment.yaml in kubernetes

```
spec:
  template:
    spec:
      containers:
          readinessProbe:
            httpGet:
              port: 8443
              path: api/actuator/health/readiness
              scheme: HTTPS
            initialDelaySeconds: 60
            failureThreshold: 2
            periodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8443
              path: api/actuator/health/liveness
              scheme: HTTPS
            initialDelaySeconds: 120
            failureThreshold: 2
            periodSeconds: 60
            timeoutSeconds: 5


```

Issue 1:
With this I started seeing issue while starting pod. I can see error message:

**Liveness probe failed: HTTP probe failed with statuscode: 404**

readiness probe is working as expected.
liveness probe is causing issue.

Issue 2:
If I update path in deployment.yaml
`path: api/actuator/health
`

Then pods start up fine.
I can see /actuator/health/readiness end point as :

```
{
  "status": "UP",
  "components": {
    "db": {
      "status": "UP",
      "components": {
        "readDataSource": {
          "status": "UP"
        },
        "writeDataSource": {
          "status": "UP"
        }
      }
    }
  }
}
```
but for liveness endpoing: /actuator/health/liveness

I get error like 404 not found.

is it something I am making error in application.yaml or deployment yaml?
